### ISSUE TITLE
Item 1: Consentreceipt.org - 

### ISSUE THREAD

**Issue by prhana** [OpenConsent/openconsentgroup#10]
Links to the website consentreceipt.org are down with the exception of : http://consentreceipt.org/consent-receipts-for-website-logins/  

Can content for each page requested to be ported to the new website, be stored as individual files in this repo?

**Comment by smartopian** [comment]
Ok, I will take down the landing page so that their is no access problems.

**Comment by prhana** [comment]
Thank you. It is working!
