### ISSUE TITLE
Point subdomain api.Openconsent.net to Didars Heroku Server 

### ISSUE THREAD

**Issue by prhana** [OpenConsent/openconsentgroup#12]

**Comment by smartopian** [comment]
please provide the DNS details

**Comment by dazzaji** [comment]
I can point this one Mark.  It's in my godaddy account admin console. 

Once Didar provides the needed DNS configuration details, I'll get right on it. 

   _________
   |   Daniel "Dazza" Greenwood, JD
   |   Personal: DazzaGreenwood.com
   |   Consulting Service: CIVICS.com
   |   MIT Research: Law.MIT.edu
   |     Email: dazza@CIVICS.com
   |     Mobile: 617.500.3644

**Comment by dazzaji** [comment]
Awaiting response from @didaralam with the DNS details needed.  If this item has been overtaken by events, then it is possible to use the alternative "default" URL provided for the herokuapp projects(eg: this site here https://boiling-caverns-7193.herokuapp.com).  It may be easier to point the second level domain (ie: OpenConsent.net) and more difficult to point the third level domain (ie: "API.OpenConsent.net) to the herokuapp.
