### ISSUE TITLE
Scheduling Mid-Project Review

### ISSUE THREAD

**Issue by dazzaji** [OpenConsent/openconsentgroup#14]
## Please Use Comments to Suggest and Agree Mid-Project Review Day and Time

All - it appears we are ready to at least schedule the mid-project review.  Please use the comments to this issue to communicate potential day-time blocks for this review session and to close the issue when a day-time is set. 

## Status: Things are on track

The current artifacts are located here: https://github.com/MassachusettsLegalHackers/orgsetup and the documentation is hosted on Wiki pages here: https://github.com/MassachusettsLegalHackers/orgsetup/wiki and it is pointed to from "openconsent.net" here: http://openconsent.net 

The requirement for the mid-project review is that each item exist at a URL and each item does.  Better yet, the most difficult aspect has been done, which is independent install, configuration, deployment and testing of the API.  This step has been documented such that any person with no prior knowledge of this project should be able to achieve the same results.  

Also, this project is being developed in a way that will ensure all resources exist within a single, version controlled environment and no resources that are needed as an essential part of the project exist "out of band" at external sites that may be changed or deleted at any time.  This common project management and documentation risk is being handled by keeping all resources available within GitHub repositories that can be forked at any time while ensuring downstream developers that fork the project have all essential resources needed to understand and see working examples and re-deploy the project themselves.  

## What remains to be completed

At a high level what remains is to duplicate the working externalize "button" (form) an example of which is currently operating at Kantara.  The plan is to take the same form as exists on the API page and ensure it is possible to deploy and operate it from an external third party site and to document the steps needed for that.  There are open issue items seeking assistance getting all relevant code by which the example externalized form and submit button have been implemented at the Kantara site.  This will assist in working with the code and making the best possible deliverable for this item. 

## Why is this work happening outside OpenConsent GitHub org?

This is a forked repo from the OpenConsent GitHub organization, which was a necessary step due to lack of rights in OpenConsent organization and the repo OpenConsentGroup or the repo OrgSetUp.  The repo OpenConsentGroup, which was originally intended to be the dev repo, has apparently been used for other purposes and the links have been disrupted based on actions by the project owner.  This is fine, given the repo name "group" suggests that repo may be used for purposes of an organization and subject to these types of unplanned and unannounced changes in setup.  However, to ensure a stable development environment, this is not compatible or workable in the short time frames alloted for this project.  Therefore, the repo "OrgSetup" is being used for dev work and as the example setup that organizations would use to adopt and deploy consent receipt API and/or the "button".  And due to lack of rights in the OpenConsent org or the OrgSetup repo in the OpenConsent org, that repo has been forked and the development work for this project is being done at the forked version which, again, is here: https://github.com/MassachusettsLegalHackers/orgsetup

## Immediate Next Steps:

(1) Communicate potential day-time slots for Mid-Project review in comments below

(2) Project owner should provide sufficient rights to the contractor(s) and project guarantor for read-wright-admin to at least the OrgSetup repo in the OpenConsentGroup GitHub organization.  If this is done, then this project will go smoother and better. 

(3) Review all remaining open issues and close those that no longer need to be open, make progress on those that remain open, and be prepared to discuss and close all open items or have a good quick plan to close all open items before the Mid-Project review meeting starts.

I apologize if I have misrepresented or incorrectly stated any fact or factor in the above.  If I have, please include any corrections or improvements in the comments to this GitHub Issue.

**Comment by prhana** [comment]
Can we schedule for Wednesday or Thursday between 9am-1:30pm? Tomorrow during the day will not work since Didar and I have opposite schedules. We are also available tomorrow night after 10pm.

**Comment by dazzaji** [comment]
I'm open (at this point) from 11-1:30 on both Wed and Thur.

**Comment by dazzaji** [comment]
@smartopian - we await your input on this.

**Comment by smartopian** [comment]
I am available now at the earliest of convenience, and I have just switched into your time zone.  So, we can have meetings later.

**Comment by prhana** [comment]
Can we schedule for tomorrow at 11am then?

**Comment by smartopian** [comment]
I can confirm I am available at 11:30 am est, shall we chat via hangout?

**Comment by dazzaji** [comment]
awesome!  i'll be there too.  hangout is best.

   _____________
   |   Daniel "Dazza" Greenwood, JD
   |   http://www.DazzaGreenwood.com
   |   617.500.3644 & dazza@CIVICS.com
   |   Actively at: Law.MIT.edu & CIVICS.com
   |   1 Broadway, 14th Fl, Cambridge, MA 02142

**Comment by prhana** [comment]
Ok, great. See you both then.

**Comment by dazzaji** [comment]
This is now scheduled for 11:30am Eastern Time on December 9th, 2015 so this issue is closed.
