### ISSUE TITLE
Access credentials for WP and Host Papa

### ISSUE THREAD

**Issue by prhana** [OpenConsent/openconsentgroup#2]
In order to complete Item 1, I will need access credentials for WP and HostPapa.

**Comment by dazzaji** [comment]
Caitlin - why do you need that?  The idea for #1 is it all happens on the GitHub pages site.  You can just copy and past the information on the handful of pages we identified in the Item 1 description and I do not see what you need access for.  Can you explain?

**Comment by dazzaji** [comment]
There are optional items for Mark that include blinging out and powering up the wordpress site and you are at liberty to do that.  That would prob need or benefit from admin access to the blog.  That is not same as Item 1 however.  Am I missing something here?

**Comment by prhana** [comment]
You are right, I just realized that I dont need those things since there is no code or anything that needs to be ported.

**Comment by dazzaji** [comment]
Ok, glad it worked out.  Case closed!
