### ISSUE TITLE
Do we use MaterializeCSS/html or best to have individual files for each page?

### ISSUE THREAD

**Issue by prhana** [OpenConsent/openconsentgroup#6]
Can WP content be added to the existing MaterializeCSS/html file in the OpenConsent GitHub Repo or best to create individual files for each page?

**Comment by dazzaji** [comment]
I am a little confused by the idea that using materializeecss on the one
hand and having more than one html page that uses materializecss on the
other hand are  necessarily different. The one page site is a classic but
many (most?) people also use materializecss on multi-page sites.  So - I
think it best to use the template Mark started with at least as a start and
to ask the question: how many pages are appropriate for this site?

Short answer: if you can fit everything on one page and it
looks/feels/works well, then do that.  If you can't fit it on one page,
then be thoughtful about how best to split up the content into more than
one page and try it out.

The longer answer is - it depends.

In general I suggest thinking of this as a fit-to-purpose software project
site and not as a publishing platform intended to support a lot of authors
and lines of content. The other factor is that, in general, fewer pages
will likely be easier to design/develop and definitely easier to maintain
and change for the foreseeable future.  The entire active community of
participants and active contributors is quite small (think: workgroup or
subcommittee) and at this point I  believe the plan is for almost all
content (not machine code) to be published through a wordpress blog.  So,
all in all, I think it is worth exploring how the site and page could work
if all the content were literally added into the current frame of the
template and if it seems to unwieldy then fall back to create only as many
additional pages or other content locations (eg GitHub Wiki page, README
file, etc) as is really needed.

The caution here is to be very sparse with the number of pages and amount
"going on" with this website.  This site is intended to serve a practical
functional role to help people find, understand, use and in some cases
contribute back to the code base.  Accordingly, the main "content" will be
the developer guides you are working on and the videos, all of which should
support and reflect the code base in the same GitHub repository that the
site is in.

It would be good to look over the Wordpress blog again and the emerging
site structure for the GitHub developer-oriented site to start identifying
the main places each site can and should cross-reference and cross-link to
the other site.  A simple linked cross-reference bridge point would be a
top-level menu item on the blog linking to "GitHub" and a top-level menu on
the GitHub pages site would link to the "Blog".  I suspect there would be
one or more other key junctures that would benefit from building in a
bridge cross-linking the two sites together or at least a deep level
gateway funneling from one site to the other (eg is people are reading
about the standards group Kantara on the GitHub dev site then a big link to
Kantara would be very fitting.


   _____________
   |   Daniel "Dazza" Greenwood, JD
   |   http://www.DazzaGreenwood.com
   |   617.500.3644 & dazza@CIVICS.com
   |   Actively at: Law.MIT.edu & CIVICS.com
   |   1 Broadway, 14th Fl, Cambridge, MA 02142
