### ISSUE TITLE
Code For Functioning Consent Receipt Form Submission

### ISSUE THREAD

**Issue by prhana** [OpenConsent/openconsentgroup#8]
Submit button works for this link: https://kantarainitiative.org/signup/?selectedGroup=3 

Didar could not make the submit button work on the following form: https://ciswg.herokuapp.com/. We have access to the code for that form. Has this form ever worked to generate a Consent Receipt for you? If not, then this form and corresponding JS code need to be fixed. Alternately, would you be able to supply us both form and JS code for the form that is working? Or a screen shot of the functional input in that form that actually  worked for you, it failed for us on form validation.

**Comment by didaralam** [comment]
Ok here is the update:

1. I'm able to deploy client and server code base into heroko (for Node.js)
2.  I understand how client side code (html/js) and server side code work (Node.js)
3.  Caitlin was able to generate receipt from the Consent receipt for and we have access to corresppmding html/js code

So, remaining tasks are

1. Create a 3rd Party client site for demo and integrate the API call
2. Write 'how to' docs

**Comment by dazzaji** [comment]
Didar, to clarify,  is this issue 8 now resolved  and if so, is the API server code installed and working in the same server that you intend to deliver or does it still need to be ported to a different instance that Mark owns and controls?

**Comment by dazzaji** [comment]
Can you please clarify this before the code review at 10:30 PM tonight? If not that is OK and we can pick it up during the code review if necessary.

**Comment by dazzaji** [comment]
Evidently this issue is also resolved.
