### ISSUE TITLE
Project Flow

### ISSUE THREAD

**Issue by dazzaji** [OpenConsent/openconsentgroup#9]
@prhana and @didaralam can we recently touch base tomorrow at some point to check in on overall progress and establish a date that can be proposed for the mid project review?

**Comment by dazzaji** [comment]
Correction: I was trying to write "can we briefly check in" not "recently"… And my phone client does not allow me to edit the issue!

**Comment by prhana** [comment]
Haha, Yes, we can check in around 6pm if that works for you.

**Comment by dazzaji** [comment]
Done!

**Comment by dazzaji** [comment]
This has been done.
